apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TruYum
  template:
    metadata:
      labels:
        app: TruYum
    spec:
      containers:
      - name: truyumrepos
        image: truyumpcheck1.azurecr.io/truyumrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: truyum
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: TruYum